# Generated by Django 5.0.4 on 2024-05-07 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='holder_name',
            new_name='lead_name',
        ),
    ]
