# Generated by Django 5.0.4 on 2024-05-22 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('leads', '0003_rename_holder_name_leads_lead_name'),
        ('sales_rep', '0004_salesrep_city_salesrep_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leads',
            old_name='lead_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='leads',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='leads',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='leads',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='leads',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='LeadScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
            ],
            options={
                'unique_together': {('lead', 'sales_rep')},
            },
        ),
        migrations.AddField(
            model_name='leads',
            name='leadSalesRepScore',
            field=models.ManyToManyField(through='leads.LeadScore', to='sales_rep.salesrep'),
        ),
        migrations.CreateModel(
            name='LeadChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'unique_together': {('lead', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='LeadOutreachTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
            ],
            options={
                'unique_together': {('lead', 'sales_rep', 'trial_number')},
            },
        ),
    ]
