# Generated by Django 5.0.4 on 2024-05-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_rename_lead_name_leads_name_remove_leads_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadchannel',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LeadOutreachActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('lead_outreach_trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leadoutreachtrial')),
            ],
        ),
    ]
