# Generated by Django 5.0.4 on 2024-05-27 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_leadchannel_username_leadoutreachactivities'),
        ('sales_rep', '0014_alter_salesrepprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadscore',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='leads',
            name='leadSalesRepScore',
        ),
        migrations.AddField(
            model_name='leadscore',
            name='sales_rep_profiles',
            field=models.ManyToManyField(to='sales_rep.salesrepprofilelist'),
        ),
        migrations.RemoveField(
            model_name='leadscore',
            name='sales_rep',
        ),
    ]
