# Generated by Django 5.0.4 on 2024-05-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('leads', '0006_alter_leadscore_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_message', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='leadoutreachactivities',
            name='channel_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.channelactivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leadoutreachactivities',
            name='status',
            field=models.CharField(default='scheduled', max_length=255),
        ),
        migrations.AddField(
            model_name='leadoutreachactivities',
            name='error',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.error'),
        ),
        migrations.AlterField(
            model_name='leadoutreachactivities',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leads.message'),
        ),
    ]
