# Generated by Django 5.0.4 on 2024-06-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_error_message_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leads',
            new_name='Leadv1',
        ),
    ]
