# Generated by Django 5.0.4 on 2024-06-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_rename_leads_leadv1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadv1',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
