# Generated by Django 5.0.4 on 2024-06-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_alter_leadv1_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadv1',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
    ]
