# Generated by Django 5.0.4 on 2024-06-04 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('leads', '0010_leadv1_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channelactivity')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leadoutreachtrial')),
            ],
        ),
    ]
