version: "3"

services:
  web:
    restart: always
    build: .
    expose:
      - "8000"
    links:
      - redis:redis
    volumes:
      - web-django:/usr/src/app
      - web-static:/usr/src/app/static
    env_file: .env
    environment:
      DEBUG: "true"
    entrypoint: ["/bin/bash", "+x", "/entrypoint.sh"]

  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443" # Added to expose port 443 for SSL
    volumes:
      - web-static:/www/static
      - letsencrypt:/etc/letsencrypt # Mount LetsEncrypt certificates
    links:
      - web:web
    # command: ["/bin/sh", "-c", "while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g 'daemon off;'"] # Renew SSL certificates every 6 hours

  certbot:
    image: certbot/certbot
    volumes:
      - letsencrypt:/etc/letsencrypt
      - web-static:/static/
    command: certonly --non-interactive --agree-tos --nginx -m "tomek@boostedchat.com" -d "webhook.boostedchat.com"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  mqtt:
    image: darwinokuku909/bst-mqt
    restart: always
    depends_on:
      - web
    ports:
      - "1883:1883"
      - "8883:8883"
      - "3000:3000"
    volumes:
      - ../mqtt-logs:/usr/src/app/logs
    environment:
      - IG_USERNAME=${IG_USERNAME}
      - IG_PASSWORD=${IG_PASSWORD}
      - API_BASE_URL=${API_BASE_URL}
      - IG_PROXY=${IG_PROXY}
      - CLIENT_ORG=${CLIENT_ORG}
      - SENTRY_DSN=${SENTRY_DSN}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - EMAIL_RECIPIENTS=${EMAIL_RECIPIENTS}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}


volumes:
  web-django:
  web-static:
  redisdata:
  letsencrypt:
