# Generated by Django 5.0.4 on 2024-05-22 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('sales_rep', '0004_salesrep_city_salesrep_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrep',
            name='full_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrep',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
        migrations.CreateModel(
            name='SalesRepChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('available', models.BooleanField(default=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timezone', models.CharField(max_length=255)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
            ],
            options={
                'unique_together': {('sales_rep', 'channel')},
            },
        ),
        migrations.CreateModel(
            name='SalesRepChannelActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('max_capacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channelactivity')),
                ('sales_rep_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepchannel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepChannelRunningAverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('average', models.IntegerField()),
                ('sales_rep_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepchannel')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepsChannelWorkingShifts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField()),
                ('shift_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.channel')),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepChannelWorkingShiftErrors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('code', models.IntegerField()),
                ('level', models.IntegerField(default=0)),
                ('sales_rep_channel_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepschannelworkingshifts')),
            ],
        ),
        migrations.CreateModel(
            name='SalesRepChannelWorkingShiftActivities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepchannelactivities')),
                ('sales_rep_channel_shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepschannelworkingshifts')),
            ],
        ),
    ]
