# Generated by Django 5.0.4 on 2024-05-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0005_salesrep_full_name_salesrep_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepchannel',
            name='sandbox',
            field=models.BooleanField(default=False),
        ),
    ]
