# Generated by Django 5.0.4 on 2024-05-22 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('sales_rep', '0006_salesrepchannel_sandbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepchannelactivities',
            name='activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='channels.channelactivity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesrepchannelactivities',
            name='max_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
