# Generated by Django 5.0.4 on 2024-05-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0007_salesrepchannelactivities_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesrepchannelactivities',
            name='max_capacity',
            field=models.IntegerField(default=0),
        ),
    ]
