# Generated by Django 5.0.4 on 2024-05-22 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('sales_rep', '0008_alter_salesrepchannelactivities_max_capacity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRepChannelRunningAverages',
            new_name='SalesRepChannelRunningAverage',
        ),
        migrations.RenameModel(
            old_name='SalesRepChannelWorkingShiftErrors',
            new_name='SalesRepChannelWorkingShiftError',
        ),
        migrations.RenameModel(
            old_name='SalesRepsChannelWorkingShifts',
            new_name='SalesRepsChannelWorkingShift',
        ),
        migrations.AlterUniqueTogether(
            name='salesrepchannelactivities',
            unique_together={('sales_rep_channel', 'activity')},
        ),
    ]
