# Generated by Django 5.0.4 on 2024-05-22 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0001_initial'),
        ('sales_rep', '0009_rename_salesrepchannelrunningaverages_salesrepchannelrunningaverage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRepChannelActivities',
            new_name='SalesRepChannelActivity',
        ),
        migrations.RenameModel(
            old_name='SalesRepChannelWorkingShiftActivities',
            new_name='SalesRepChannelWorkingShiftActivity',
        ),
    ]
