# Generated by Django 5.0.4 on 2024-05-22 06:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0010_rename_salesrepchannelactivities_salesrepchannelactivity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepchannelrunningaverage',
            name='sales_rep_channel',
        ),
        migrations.RemoveField(
            model_name='salesrepschannelworkingshift',
            name='shift_date',
        ),
        migrations.AddField(
            model_name='salesrepchannelrunningaverage',
            name='sales_rep_channel_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepchannelactivity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrepschannelworkingshift',
            name='end_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesrepschannelworkingshift',
            name='start_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
