# Generated by Django 5.0.4 on 2024-05-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0011_remove_salesrepchannelrunningaverage_sales_rep_channel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
            ],
            options={
                'unique_together': {('sales_rep', 'profile')},
            },
        ),
        migrations.DeleteModel(
            name='SalesRepChannelWorkingShiftActivity',
        ),
    ]
