# Generated by Django 5.0.4 on 2024-05-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0012_salesrepprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRepProfileList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='salesrepprofile',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepprofilelist'),
        ),
    ]
