# Generated by Django 5.0.4 on 2024-05-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0013_salesrepprofilelist_alter_salesrepprofile_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesrepprofile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salesrepprofile',
            name='profile',
        ),
        migrations.AddField(
            model_name='salesrepprofile',
            name='profile',
            field=models.ManyToManyField(to='sales_rep.salesrepprofilelist'),
        ),
    ]
