# Generated by Django 5.0.4 on 2024-06-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0014_alter_salesrepprofile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salesrepchannelactivity',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='salesrepchannelactivity',
            name='sales_rep_channel',
        ),
    ]
