# Generated by Django 5.0.4 on 2024-06-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0015_alter_salesrepchannelactivity_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesrepchannelactivity',
            name='sales_rep_channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrepchannel'),
            preserve_default=False,
        ),
    ]
