# Generated by Django 5.0.4 on 2024-06-03 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0016_salesrepchannelactivity_sales_rep_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepchannelactivity',
            name='sales_rep_channel',
        ),
        migrations.AddField(
            model_name='salesrepchannelactivity',
            name='sales_rep',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep'),
            preserve_default=False,
        ),
    ]
