# Generated by Django 5.0.4 on 2024-06-03 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rep', '0017_remove_salesrepchannelactivity_sales_rep_channel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesrepschannelworkingshift',
            name='shift_number',
        ),
    ]
