# Generated by Django 5.0.4 on 2024-05-07 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0002_leads'),
        ('sales_rep', '0004_salesrep_city_salesrep_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramUserNames',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(max_length=255)),
                ('status1', models.CharField(blank=True, max_length=255, null=True)),
                ('status2', models.CharField(blank=True, max_length=255, null=True)),
                ('status3', models.CharField(blank=True, max_length=255, null=True)),
                ('sandbox', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramLeadUserNames',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
                ('instagram_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.instagramusernames')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramLead',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
                ('instagram_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.instagramleadusernames')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramSalesRepUserNames',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
                ('instagram_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.instagramusernames')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramSalesRep',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sales_rep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_rep.salesrep')),
                ('instagram_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.instagramsalesrepusernames')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramSandboxUserNames',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, default=None, editable=False, null=True)),
                ('id', models.CharField(db_index=True, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instagram_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channels.instagramusernames')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
