# Generated by Django 5.0.4 on 2024-05-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0002_linkedinusernames_sandboxusernames_whatsappusernames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappusernames',
            old_name='whatsapp',
            new_name='sandbox',
        ),
    ]
