# Generated by Django 5.0.4 on 2024-05-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0003_rename_whatsapp_whatsappusernames_sandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramusernames',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='linkedinusernames',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='sandboxusernames',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappusernames',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
