# Generated by Django 5.0.4 on 2024-05-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels', '0004_alter_instagramusernames_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappusernames',
            name='sandbox',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
